import type { BookingMode } from "../config/bookingServices";
import { getOfficeLocationAddress, officeLocation } from "../config/officeLocation";

type CalLocationQueryConfig = {
  queryParamName: string;
  value: string;
};

export const calOfficeLocationDisplay = `${officeLocation.name}, ${getOfficeLocationAddress()}`;

// Complete these values only with the exact payload generated by
// Cal.com -> Event Type -> Embed -> Embed Snippet Generator.
// The physical location configured in Cal.com should match calOfficeLocationDisplay.
const calLocationConfigByMode: Record<BookingMode, CalLocationQueryConfig | null> =
  {
    online: null,
    office: null,
  };

export function getCalLocationConfig(
  mode: BookingMode,
): CalLocationQueryConfig | null {
  return calLocationConfigByMode[mode];
}

export function buildCalEmbedUrl(
  calLink: string,
  mode: BookingMode,
  retryKey: number,
): string {
  const url = new URL(`https://cal.com/${calLink}`);
  url.searchParams.set("embed", "true");
  url.searchParams.set("layout", "month_view");
  url.searchParams.set("timezone", "Europe/Bucharest");
  url.searchParams.set("_retry", String(retryKey));

  const locationConfig = getCalLocationConfig(mode);

  if (locationConfig) {
    url.searchParams.set(locationConfig.queryParamName, locationConfig.value);
  }

  return url.toString();
}
